### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by RWOverdijk** [niudai/CozyPink#1]
I cannot recommend this theme enough. After installing it my taste in fashion as well as my love for brushing hair rose to levels that cannot be imaged; only experienced. The explosion of pink that gets beamed at your face feels like an embrace which brings a certain warmth with it that can only be described as – fantastic. It's the type of warmth that lets you forget about the life of plastic and makes you long for the freedom that is imagination, only for a short while until it makes you realise that life... Well, life is your creation.

In closing I'd like to add that now every time I close my editor I feel the urge to open it again, as there's a tender whisper saying: _"Come jump in, bimbo friend, let us do it again."_.

10/10 would install again.

**Comment by niudai** [comment]
Black and white themes make you feel coding is also "black and white", which is to say, sort of hard and cold. What if the editor is based on some warm background? Maybe it would make the coding life warmer , and, maybe , make you life easier. Thanks a lot.
